### PR TITLE
[Add TTA] RotateLeft90 and RotateRight90

### PR DESCRIPTION
**Pull request by piantic**
Hi, @kentaroy47.

I added two types of TTA.
- RotateLeft90(It is same to original Rotage90)
- RotateRight90

I think it is work well but it will be good to check that it is good.
Thanks.

### CODE REVIEW

**Review by kentaroy47 — CHANGES_REQUESTED** [review]
Thanks for the PR!
Can you add imsize acquiring to batch_augment modes too?
Other than that, it works great!

eg:
```
def batch_augment(self, images):
      self.imsize = images.shape[2]
      return ~~
```

**Comment by piantic** [comment]
Hi, I miss that `self.imsize = images.shape[2]`.
And I added above code line to batch_augment.

Thanks!

**Review by piantic — COMMENTED** [review]
Add image size to batch_augment

**Comment by kentaroy47** [comment]
LGTM!

**Pull request merged**
